geotiffjs/geotiff.js

- package.json
- src/compression/deflate.js
Used https://github.com/nodeca/pako to implement deflate decoder.
Not a professional in this domain, but quick test looks like working. Would appreciate if get some feedback is this ok to do or is there something what I missed.
> Implemented DeflateDecoder by using 'pako' library

- src/compression/lzw.js
I also cleaned it up a bit and removed big-endian support and compression, which were unused.
> make lzw compression faster

- src/compression/index.js
As used by:
- GDAL https://github.com/OSGeo/gdal/blob/f8d68070da1bfef965c947242fe4f6f5fe643908/gdal/frmts/gtiff/libtiff/tiff.h#L181
- libtiff http://www.libtiff.org/man/libtiff.3t.html
> Support for DEFLATE with code 32946

- src/globals.js
- test/geotiff.spec.js
Fixes: https://github.com/geotiffjs/geotiff.js/issues/85
> Add missing entry in fieldTagTypes for GDAL_NODATA

- src/geotiffimage.js
- src/globals.js
- test/data/setup_data.sh
- test/geotiff.spec.js
Provides alpha channel support, controlled by parameter enableAlpha in readRGB function, to soleve #107
> Feature alphachannel 

- COMMUNITY.md
- README.md
per https://github.com/geotiffjs/geotiff.js/issues/123
> added community page

- package-lock.json
- package.json
- webpack.analyze.js
For your consideration, I have created a PR that adds the [Webpack Bundle Analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer).  It can help us figure out what packages and files are taking up the most space in the webpack bundle.
Here's an example of what it will look like:
Open to your suggestions and thoughts :-)
> Added Webpack Bundle Analyzer

- package-lock.json
- package.json
- src/geotiff.js
- test/data/setup_data.sh
- test/geotiff.spec.js
The handling for geotiffs with external overviews seems somewhat broken currently, for example the example in the [readme](https://github.com/geotiffjs/geotiff.js#external-overviews) doesn't work, and I think the same error I was getting is responsible for #152
I've taken a poke around and made some modifications and added a few tests to verify that I'm doing the correct thing. 
I've also added basic nodejs server to the test suite so that tiffs can be retrieved from the `test/data` directory using the `fromUrl` or `fromUrls` method (which is the only way for accessing external overviews).
> Rework handling of geotiffs with overviews

- src/geotiff.js
> Fix string data array conversion issue.

- src/compression/basedecoder.js
- src/decoder.worker.js
> async-ify decoders and await decodeBlock

- src/globals.js
> Ensure SubIFDs is an Array

- src/dataview64.js
> Fix DataView64#getFloat16 method

- src/geotiffimage.js
- test/geotiff.spec.js
Allowing option to request non-interleaved RGB data, i.e the result is an array of a red, green and blue array.
> RGB non interleaved

- src/geotiffimage.js
- test/data/setup_data.sh
- test/geotiff.spec.js
> issue-264: fixed getGDALMetadata

- README.md
- src/geotiffimage.js
- src/source/blockedsource.js
- src/source/remote.js
The branch in #224 includes changes beyond its original scope. This PR applies only the changes within the original scope.
cc: @andreasg123
> AbortController Bypasses Cache (2)

- src/geotiffimage.js
- src/source/remote.js
I can never decide on grey vs gray, so I kind of like the choice of greayscale.  But I thought maybe it should be corrected in the docs.
> Spelling fixes

- package-lock.json
- package.json
> Fix jest problem caused by quick-lru

- COMMUNITY.md
thanks for your consideration.  let me know if you have any thoughts or feedback :-)
> Added geotiff-tile to COMMUNITY.md

- README.md
> Add an example of how to use geotiff to resolve GPS to elevation

- test/data/setup_data.sh
ref https://github.com/geotiffjs/geotiff.js/issues/355
> Comment out unavailable file

- src/globals.js
> - Added field tag type for ModelTransformation tag

- src/geotiffwriter.js
Apply toArray to RowsPerStrip metadata
> Apply toArray to RowsPerStrip metadata

- src/source/client/base.js
- src/source/client/fetch.js
> Fix types of the request() method

- src/geotiffimage.js
@constantinius Fixes https://github.com/geotiffjs/geotiff.js/pull/413#issuecomment-1926475679
> Fix syntax error

- src/globals.js
Closes https://github.com/geotiffjs/geotiff.js/issues/453
> feat: add tiff tag for LSM files
