geotiffjs/geotiff.js

package.json
src/globals.js

Allows geotiff.js to work easily with node.js platforms. Requires the xmldom module from npm. 
I haven't confirmed whether this change affects browser functionality because I can't get `grunt test` to work. The server runs fine but there are not TIFF files in the test directory.

Add Node.JS compatability

---

src/main.js

If geotiff.js is imported in a Web Worker the `window` global scope is not available.  Instead, this attaches GeoTIFF to the Worker Global Scope `self`.

Make compatible with web workers

---

src/main.js

When I run `npm run build` I get the following jshint error:
`'self' is not defined` for line 36 in `src/main.js`
Here's a screenshot:
This pull request just adds a comment to that line telling jshint to skip this line
*Apologies in advance if I misunderstood something or I forgot to include some information

ignore jshint error about self being undefined

---

src/geotiff.js
test/geotiff.spec.js

Adjusted `parseGeoKeyDirectory`, so it parses the last GeoKey.  Missing the last GeoKey isn't really a big issue for thoroughly tagged geotiffs, because the last key is often something like `GeogInvFlatteningGeoKey`.  However, I've been trying to integrate with exports from geoserver via WCS, which often put `GeographicTypeGeoKey` as the last key.  Here's an example from geoserver:
http://geomap.arpa.veneto.it/geoserver/wcs?crs=EPSG%3A4326&service=WCS&format=GeoTIFF&request=GetCoverage&height=329&width=368&version=1.0.0&BBox=9.679858245722988%2C13.951082737884812%2C44.183855724634675%2C47.38727409375604&Coverage=geonode%3Aatlanteil
Link to a downloaded version on S3 if the above link doesn't work for you: https://s3.amazonaws.com/georaster/geonode_atlanteil.tif
As always, let me know if …

fixed missing last geokey

---

README.md

It looks like `npm start` was removed, `npm run dev` appears to be similar to what it use to be doing.

Correct testing commands

---

src/compression/basedecoder.js
src/predictor.js

Two issues:
- predictor was not taking into account PlanarConfiguration=Separate, which
caused errors on multi sample files
- in Predictor=3, a lack of multiplication by stride caused errors on
multi sample files with PlanarConfiguration=Contig.

predictor: fix PlanarConfiguration=Separate and Predictor=3 with multiple samples

---

src/source.js

In a HTTP GET range request, the end offset is included. Once that fixed,
we can set the block size to be 65536.

source: fix incorrect computation of range requests

---

src/geotiff.js
src/globals.js

Some cameras (Sequoia Parrot in my case) use the non-standard tag type 13 to indicate an offset to an IFD, as recommended on ExifTools homepage here: https://owl.phy.queensu.ca/~phil/exiftool/standards.html (see section "TIFF 6.0" / "A simple solution").
For GeoTiff.js' purpose, I have added the `IFD` field type to handle this, the implementation is analogous to the `IFD8` data type: 13 is handled as an unsigned 32 bit integer.
With this change, I can read GPS information from the Sequoia Parrot camera (without the change, loading a such file breaks with the error `RangeError: Invalid field type: 13`).
ExifTool does the same, so this should be safe to do.

Add support for tag type 0x0D / 13

---

src/compression/lzw.js

Some geotiff files, which are compressed with lzw, cannot be parsed and are hung out.
For example, [NASA's](https://neo.sci.gsfc.nasa.gov/servlet/RenderData?si=1716646&cs=gs&format=TIFF&width=720&height=360) (raster, lzw, big endian)
This is because current implementation has no limit for `bytelength` during lzw decompression.
According to [this](https://www.fileformat.info/format/tiff/corion-lzw.htm), the maximus is 12.
This PR set the limit and enable this lib to parse [the file](https://neo.sci.gsfc.nasa.gov/servlet/RenderData?si=1716646&cs=gs&format=TIFF&width=720&height=360).
I referred [golang's implementation](https://github.com/golang/image/blob/master/tiff/lzw/reader.go)

Fix lzw decompression

---

src/geotiffimage.js

When passing a width and height to the readRGB method and the tiff file PhotometricInterpretation is RGB the width and height are not passed along to the readRasters method

readRGB not respecting width and height

---

src/predictor.js
test/data/setup_data.sh
test/geotiff.spec.js

The last strip in a TIFF will not be padded like tiles are.  Since the actual strip height is not passed to the predictor it tried to work off the end of the array.  Fortunately we can just bail out early when we reach the end of our buffer.

Fix reading tiffs with prediction and "truncated" strips

---

package-lock.json
package.json
src/geotiffwriter.js

This pull request fixes a bug when running `npm run bundle:prod`
Although UglifyJs isn't directly used by geotiff.js, it is used by webpack.
I also replaced the `module.exports = { writeGeotiff }` in geotiffwriter.js with an `export function writeGeotiff`.  Per this conversation, https://github.com/webpack/webpack/issues/4039#issuecomment-273804003, webpack doesn't like mixing `import` with `module.exports`.  I was also running into issues when building a project that used `geotiff` as a dependency.

updated webpack and worker-loader

---

src/dataslice.js
test/geotiff.spec.js

Copying the arithmetic here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView.  Fixes  #132, Fixes #68, Fixes #63.
I think this is exclusively used for reading byte offsets, so unless someone tries to read a 9,000,000 GB file, the maximum available javascript integer of 2 ** 53 - 1 should preclude us from using `BitInt` and its performance knock.

64bit int uint

---

README.md
src/geotiff.js
src/source.js
test/geotiff.spec.js

For further information see the following
Most operating systems limit the number of file descriptors that may be open at any given time so it is critical to close the descriptor when operations are completed. Failure to do so will result in a memory leak that will eventually cause an application to crash.
from https://nodejs.org/api/fs.html#fs_file_descriptors

Close the file after reading

---

test/data/setup_data.sh
test/geotiff.spec.js

I think we just needed to get rid of the now defunct `fileDirectories` value.  I also added a test using a file I uploaded for something else that has multiple image pages.

Add multi-channel tiff and update tests

---

README.md
package-lock.json
package.json
src/main.js
src/pool.js
test/dev.js
test/geotiff.spec.js
test/source.js

This PR depends on #144. 
It changes the main entrypoint to `src/geotiff.js` as `src/main.js` isn't adding any functionality to the package and prevents some builders to find the default export.

Change the main entrypoint to geotiff.js

---

src/dataslice.js
src/dataview64.js
test/geotiff.spec.js

I hadn't noticed this class since it is only used reading the firstIFDOffset which is always (in theory) 16 for BigTiff, but I ran into some mal-formatted data so I figure this should be fixed. ~~I think we could also maybe just remove `DataView64` all together and refactor to use `DataSlice`?~~  Open to suggestions.
EDIT: I realized that this method is static and the class hasn't been instantiated yet.  Still open to other fixes if you think of anything!

Fixed DataView 64 bit parsing

---

src/decoder.worker.js
src/pool.js

Using `Transfer` to avert copying of data buffers to workers and back again

---

src/geotiffimage.js

When image.getGDALMetadata(sample) is called with 0, if(sample) returns false, so the metadata is not filtered properly to the required sample. As a result, some metadata can be overwritten by the last sample of the image.

fix: impossible to get sample 0's metadata

---

package-lock.json
package.json

We currently use a fork of `geotiff.js` for our [`viv`](https://github.com/hms-dbmi/viv) project, and installation requires building our fork from source. One of our users [ran into an issue](https://forum.image.sc/t/viv-and-avivator/45999) with building geotiff and I think it's related to: https://github.com/geotiffjs/geotiff.js/issues/58
This PR: 
- adds `rimraf` as a cross-platform dependency for performing `rm -rf` in `build:clean`

Use rimraf for cross-platform rm -rf

---

src/pool.js

Make worker a constructor param so when using geotiffjs as a webpack dependency, we can use a worker loader externally to initialise decoder worker and pass it to Pool.

Make decoder.worker a constructor param in Pool

---

src/geotiff.js

It looks like the `getImage` method of a `MultiGeoTIFF` doesn't properly assign geo keys to the image.  It looks like it was a typo to try to access the `imageFile. geoKeyDirectory` property.
I don't see existing tests for a `MultiGeoTIFF`.  Any suggestions on putting together suitable test data?

Get geo keys from image file directory

---

src/source.js

Some HTTP servers do not support Range requests when the Range header is longer than the actual length of the file. Examples of servers that don't support it are Aliyun OSS (see #196 and examples below, and it looks like [node-static](https://github.com/cloudhead/node-static/issues/212) also doesn't support it).
I was reading through [RFC 7233: Range Requests](https://tools.ietf.org/html/rfc7233#section-3.1) but it doesn't seem to say anything about what servers should do when the byte range is longer than the file range. So I guess Aliyun OSS is technically in the spec when they don't support it, and it's something we need to handle on the client side.
Fixes #196
The length of the following file is `44515988` bytes.
**Returns HTTP 200**
The following HTTP range request returns HTTP 200 …

Limit maximum HTTP Range header to fileSize

---

src/source/remote.js

In commit 3f129bbcc1025be786da34216ba40c05ad495eea, where the http files were restructured, it looks like the `import http` was not added to the new file.
This causes a 'ReferenceError: http is not defined' when trying to get a geotiff.
I've removed the `if (http.get)` condition, since normally, it should never fail.
If we are running on a browser, fetch() should exist for any new browser, otherwise XMLHttpRequest would exist, so the function would return early and never reach `if (http.get)`.
Therefore, we must be running on Node.JS, where the http library exists.

Fix undeclared `http` variable for Node.js

---

src/source/blockedsource.js
test/geotiff.spec.js

I am going through the latest changes now @constantinius to try to prepare to rewrite #182 and I think that I came across what seems like two small bugs.
1. I think we want to use `sortedBlockIds` for iteration, not `blockIds` because the loop relies on the ordering to create what were formerly known as "coherent" blocks.
2. If we set `lastBlockId` to `null` in the last statement, then the current `blockId` then `current.push(blockId);` is called on thenext `blockId` regardless of what the last one was, which could cause two blocks that are not consecutive to be in the same group.
I created a branch of Viv to test it out if you want to pull it down and build it (it uses 1.0.2 of geotiff) to see this happen live: https://github.com/hms-dbmi/viv/tree/ilan-gold/geotiff_bug_report
If open …

Fix Block Grouping Bug

---

README.md
package.json
src/compression/index.js
src/compression/lerc.js
src/globals.js
test/data/setup_data.sh
test/dev.js
test/geotiff.spec.js

Until GDAL 3.3 is released, test files currently must be generated with GDAL compiled with internal libtiff. I used [osgeo/gdal](https://hub.docker.com/r/osgeo/gdal) in Docker.
Fixes #205

Add LERC compression support

---

COMMUNITY.md
README.md

This PR:
1. Adds references to `geotiff-geokeys-to-proj4` to `COMMUNITY.md` and `README.md`.
2. Removes "Parsing of EPSG identifiers" from "Planned stuff" section since this library has taken care of that task.
3. Fixes #229

Add references to geotiff-geokeys-to-proj4

---

src/compression/index.js
src/decoder.worker.js
src/geotiff.js
src/geotiffimage.js

- Adding a new decoder to `geotiff.js` requires increasing the overall bundle size. End-users "pay" for _all_ the decoders upfront, regardless of whether they are used in an application.
- There is no way for a library user to "swap" out a decoder implementation if desired. E.g. in our usage of `geotiff.js` we decided a WASM LZW decoder suited our needs from a performance perspective, but there was a tension with whether this module should live in geotiff.js due to the increase in bundle size. https://github.com/geotiffjs/geotiff.js/issues/172#issuecomment-688921489. 
We have subsequently had to live on a fork of geotiff.js, and it would be great to move towards a solution that provides the flexibility we'd desire (as "advanced" users) while keeping sensible defaults. 
Create an internal …

Create (public) dynamic decoder registry

---

package-lock.json
package.json
src/compression/deflate.js
src/compression/lerc.js
src/geotiffimage.js
src/source/file.js

**TL;DR** *modern bundlers (vite, esbuild, rollup) can bundle geotiff from source with (near) "zero-config"*
geotiff.js can be a little tricky to bundle from source if you're not using webpack or parcel. This primarily adds/changes fields in the `package.json` to improve "zero-config" bundling by several modern bundlers.
1.) bump `txml` and `pako` to latest ESM versions.
2.) add a ["browser"](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module) field to the `package.json` with `false` for Node builtins. 
```json
"browser": {
"fs": false,
"http": false,
"https": false,
"url": false
},
```
This field is recognized by `webpack`, `esbuild`, `vite`, and `@rollup/plugin-node-resolve` (official node resolution plugin for `rollup`). This field tells bundlers to import an …

Improve bundling of geotiff.js with `rollup`, `esbuild` and `vite`

---

package.json
src/browser/txml.js
src/geotiffimage.js
src/txml.js

This pull request adds an appropriate alias for `txml` in `package.json`'s `"browser"` section, fixing the import in `geotiffimage.js` to work correctly in node, and removing the `"alias"` section in 'package.json`, which is no longer needed.
With this change, txml should work both in node (with `transformStream`) and browsers (using the recommended `txml/dist/txml` module, see https://github.com/TobiasNickel/tXml/blob/45566897f576558c1c5faaac47f3fdf9177adf49/README.md#installation).
Fixes #241.

Fix txml imports and alias

---

src/geotiffimage.js
test/geotiff.spec.js

It looks like pixel values that fall outside the image dimensions (to the right or bottom) are assigned a value of 0.  This is especially apparent when an overview image is smaller than the internal tile size.  In this case, the nodata or `fillValue` is not respected for the pixels to the right or below the image extent.  See https://github.com/openlayers/openlayers/issues/12838#issuecomment-933398159 for an example that reproduces this in the OpenLayers GeoTIFF source.
This change makes it so tile or strip values that come from x >= imageWidth or y >= imageHeight are not read into the values array.  This makes it so any user-provided `fillValue` is respected in those regions.

Avoid reading tile values outside image dimensions

---

.github/workflows/ci.yml
package-lock.json
package.json
src/geotiffimage.js
test/data/setup_data.sh
test/geotiff.spec.js

This pull request introduces [xml-utils](https://github.com/danieljdufour/xml-utils) and removes txml.  xml-utils doesn't have any dependencies (other than the test runner [flug](https://github.com/danieljdufour/flug) for development) and it doesn't use any NodeJS builtins.  There shouldn't be any configuration required for use with webpack or any other bundler.  This should fix https://github.com/geotiffjs/geotiff.js/issues/241
Note: I didn't see any tests covering getGDALMetadata, but I might have missed them.  I don't have time at the moment to add any more tests (prepping for FOSS4G!), but would have time in a week or so.

replaced txml with xml-utils

---

.eslintrc.cjs
package.json
src/compression/basedecoder.js
src/compression/deflate.js
src/compression/index.js
src/compression/jpeg.js
src/compression/lerc.js
src/compression/lzw.js
src/compression/packbits.js
src/compression/raw.js
src/decoder.worker.js
src/geotiff.js
src/geotiffimage.js
src/geotiffwriter.js
src/source/arraybuffer.js
src/source/blockedsource.js
src/source/client/fetch.js
src/source/client/http.js
src/source/client/xhr.js
src/source/file.js
src/source/filereader.js
src/source/remote.js
test/dev.js
test/geotiff.spec.js
test/source.js

This pull request takes the minimal changes from @tschaub's [vite](https://github.com/tschaub/geotiff.js/tree/vite) branch (see https://github.com/geotiffjs/geotiff.js/pull/242#issuecomment-936776217) to make geotiff.js work with vite. The only changes are that all local imports now have a `.js` extension, and `package.json` got a `"type": "module"` entry and an `"exports"` map.
This is a **breaking change** for those who had to work around issues with the `geotiff` package by importing modules from `geotiff/src/geotiff.js` instead of just `geotiff`.

Make sources and package ES module compliant

---

package.json

I noticed that v2.0.0 was not correctly published:
* The package contains a `src/` directory, which should be excluded thanks to `.npmignore`.
* The package does not contain a `dist-module/` directory, which should be created in the process of `npm publish`
This pull request fixes both. When merged, v2.0.1 should be published.

Fixes for correct result of npm publish

---

src/geotiff.js
src/pool.js

Now that types are published, it is imporant that async functions have the correct `@returns` type, i.e. a `Promise`. Also, functions that are not async should not have the `async` keyword.
This pull request fixes that.
It would be good if a patch release could be published when this is merged. This is the last showstopper for updating geotiff to v2 in OpenLayers. See openlayers/openlayers#13292.

Fix types and remove unnecessary async

---

src/geotiff.js
src/geotiffimage.js

This pull request makes working with geotiff.js in typed environments easier:
* Export  `GeoTIFFImage` so it is directly available as `import { GeoTIFFImage } from 'geotiff'` instead of `import GeoTIFFImage from 'geotiff/dist-module/geotiffimage.js'`
* Fix `GeoTIFFImage`'s `TypedArray` type references

Make GeoTIFFImage available and fix its type imports

---

COMMUNITY.md

Hello.  I created a library [geotiff-precise-bbox](https://github.com/GeoTIFF/geotiff-precise-bbox) to calculate the bounding box while avoiding floating-point arithmetic.  There can be minor imprecisions using `image.getBoundingBox()` .  If it makes sense, I'm happy to try to add this functionality directly into geotiff.js. Also, happy to leave it as a separate community project.  Whatever makes the most sense to you :-)
Thank you for your consideration.

Added geotiff-precise-bbox to COMMUNITY.md

---

package.json

Fixes #261.
It looks like the `"browsers"` entry under `"engines"` in `package.json` was made for parcel, which is no longer used. Since that field causes warnings when using yarn, I think it makes sense to remove it.

Remove unused browsers engine

---

src/geotiff.js

It currently isn't possible to implement a custom decoder that inherits from `BaseDecoder`, since the class is not exported. This PR exports the base class so that end users can extend for their custom use cases. 
This is important for us to replace the builtin lzw decoder.

feat: export BaseDecoder

---

package-lock.json
package.json
src/source/blockedsource.js

Hey, really sorry about this. Opened the last PR prior to testing locally. It seems there are additionally differences between the latest lru-cache (besides using `.delete`). A `cacheSize` of 0 is not supported and throws an error, for example, breaking our suggestion in the README.
This PR reverts to the old version of `lru-cache` and uses the `.del` method. I think a subsequent PR, if ever, should be the place to migrate to a new major version.
I have tried this branch out in `viv` and things seem to be working.

Replace `lru-cache` with `quick-lru`

---

src/geotiffimage.js
src/source/blockedsource.js

There are a few TS errors in the generated types making it difficult for consumers to use this library.
This also bumps the patch version so a new version can be published.
Fixes #286﻿

Fix TS types for references that do not point to objects

---

src/geotiff.js
src/geotiffimage.js

According to the README (as quoted below), a call to `readRasters()` attaches `height` and `width` to the returned array.
Before this PR, the return type of `readRasters()` was `Promise<TypedArray | TypedArray[]>`, which does not include the `height` and `width` fields.
For convenience the result always has a width and height attribute:
```javascript
const data = await image.readRasters();
const { width, height } = data;
```
Alter the return type of `readRasters()` to a new type named `ReadRasterResult`, which extends `TypedArray | TypedArray[]` to include `{ height: number; width: number }`.

TypeScript: add `height` and `width` to return type of `readRasters()`

---

README.md

That was fixed when I reworked the build process.

GeoTIFF.Pool does work with the browser full build

---

package.json

This pull request improves the developer experience for TypeScript users and users of smart JS editors that provide type hints. This is achieved by properly mapping types to exports in package.json.

Map .d.ts files in package.json

---

README.md
src/source/blockedsource.js

Fixes #318 and the problems reported in the aftermath of #284.
The problem after #284 is that when the `cacheSize` is smaller than the number of blocks for one set of requests, blocks that were properly loaded are not available because they were evicted from the cache already. With this change, the last evicted set of blocks is still available during the whole process of fetching a set of blocks.
I also removed the note in the README about setting `cacheSize: 0`, because `quick-lru` does not even accept `0` as cache size, and I think the problem that led to that note in the README no longer exists with this pull request.

Fix cache handling issues that caused an AggregateError

---

src/geotiffimage.js

For details and example images please see this issue: https://github.com/openlayers/openlayers/issues/14238
It looks like for GeoTiffs with a ModelTransformationTag the 5th element needs to be negated. It works for my example images, but I'm not sure whether that has any side effects. What do you GeoTiff experts think?
Related issue: https://github.com/geotiffjs/geotiff.js/issues/40

Fix resolution detection for ModelTransformation

---

README.md

Because of the following the `writeArrayBuffer` example does not work.
https://github.com/geotiffjs/geotiff.js/blob/4f4d116667b6a6aa67c57a91e4a8a6ed3905c0bd/src/geotiffwriter.js#L367-L373
Add `GeographicTypeGeoKey` for `ModelTiepoint` to be used.
```js
import { writeArrayBuffer } from 'geotiff';
const values = [1, 2, 3, 4, 5, 6, 7, 8, 9];
const metadata = {
GeographicTypeGeoKey: 4326,
height: 3,
ModelPixelScale: [0.031355, 0.031355, 0],
ModelTiepoint: [0, 0, 0, 11.331755000000001, 46.268645, 0],
width: 3
};
const arrayBuffer = await writeArrayBuffer(values, metadata);
```

Set `GeographicTypeGeoKey` in example

---

src/geotiffimage.js
test/data/setup_data.sh
test/geotiff.spec.js

GeoTIFFImage doesn't currently factor in skew/rotation when calculating the bounding box.  This code updates getBoundingBox to make use of the relevant skew/rotation parameters in the ModelTransformation tag.  The new code only runs if a ModelTransformation tag is present.  If there isn't one, the code runs as it currently does.
I also added a test using a geotiff I added to https://github.com/geotiff/test-data.  It's clipped from a geotiff from Umbra's open data program.  The issue that kicked this off is here: https://github.com/stac-utils/stac-layer/issues/61#issuecomment-1518241405 
I've attached a screenshot from QGIS illustrating the change:
Thank you for your consideration and please do let me know if there is any feedback or any requested changes.  Open to your thoughts :-)
cc …

improved getBoundingBox support for skewed/rotated images

---

src/geotiff.js
src/source/remote.js

This PR exposes the `BaseClient` and `BaseResponse` classes in the API, as well as a new builder function: `fromCustomClient()`. `fromCustomClient` is used to build a `GeoTIFF` object from a user-provided client (that implements `BaseClient`).
The use case is when the user is not satisfied with the available clients (fetch, XHR, HTTP), and must use their own client.
Fix #368

Make it possible to build a RemoteSource with a user-provided client

---

src/geotiffimage.js

Uses the same block data for all bands.  Fixes #376.

Avoid redundant reads of pixel-interleaved files

---

src/globals.js

Fixes https://github.com/geotiffjs/geotiff.js/issues/384

Add fieldTagNames for GeoDoubleParams metadata

---

src/geotiffwriter.js

Fix bug in geotiffwriter.js: Correctly remove geokeys from metadata

Correctly remove geokeys from metadata

---

.github/workflows/ci.yml
package-lock.json
package.json
scripts/serialize-workers.cjs
src/compression/index.js
src/compression/lerc.js
src/globals.js
test/data/setup_data.sh
test/geotiff.spec.js
test/source.js
tsconfig.json

I noticed that [Planetary Computer COGs](https://planetarycomputer.microsoft.com/dataset/3dep-lidar-dsm) are compressed with `LERC_ZSTD` and could not be read by `geotiff.js`.
I fumbled around a bit to figure out a working implementation of the [Zstandard](http://facebook.github.io/zstd/) decoder since there's a couple Javascript ports, so I figured I'd make this PR in case it can be improved or merged.
The [`zstddec`](https://www.npmjs.com/package/zstddec) library utilizes WebAssembly (which I'm rather unexperienced with) and getting it properly initialized was the main pain point; I'm sure it could be cleaner but this appears to work for me.
The `"DOM"` types in tsconfig appear to be necessary (based on https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/826) but there …

Added LERC_ZSTD decompression

---

src/geotiffimage.js

The change introduced by #361 is not useful for OpenLayers which now has to duplicate the original code.  An option to return the original value as a tilegrid extent would be more maintainable than duplication of code.

getBoundingBox tilegrid option

---

src/source/client/base.js
src/source/client/fetch.js

This PR fixes bug explained in #415 .
It seems someone who developed this code wanted to move credentials option into RemoteSource class; but then forgot to complete the work and made code non-working. The PR undoes this effort and makes the code work again.

Bugfix: remove needless credentials argument

---

src/geotiffimage.js

Replaces #403 where the Y axis resolution should have been negated

Calculate resolution correctly for rotated rasters

---

package.json
src/geotiff.js
src/globals.js
test/globals.spec.js

Add function to register additional non-standard tags that are then able to be parsed
Add tests for that function

feat: keep a separate map of tag IDs to parsed IFD values in `ImageFileDescriptor` object

---

src/geotiffimage.js

Fixes the return type of the `getTileOrStrip` method on the `GeoTIFFImage`.

fix: getTileOrStrip return type

---

package-lock.json
package.json
src/geotiffimage.js

I'm optimistic that this would fix https://github.com/geotiffjs/geotiff.js/issues/446 where we use the correct xml-utils file depending on whether we are in a CJS or ESM environment.
Open to feedback, because I'm not 100% sure.

upgraded xml-utils to newest version with fix for #446

---

src/geotiffimage.js
test/data/setup_data.sh
test/geotiff.spec.js

This adds support for sparse tiff files, where the tiff file contains tiles or strips with both index and byte count set to zero.
When reading such a tile, we create an array of the appropriate type and size, and fill it with the GDAL nodata value if that is set, or otherwise with zero, as specified in https://gdal.org/drivers/raster/gtiff.html#sparse-files.
Includes some tests with 8-bit and 16-bit sparse tiff files.
Closes #304

Support sparse tiff files

---

README.md
src/geotiffimage.js

This PR fixes documentation that mention that `readRGB()` always interleave pixels (it does not if `interleave: false` in the options).
There is even an existing test case that proves it:
```js
it('should read into non-interleaved arrays if requested', async () => {
const tiff = await GeoTIFF.fromSource(createSource('rgb.tiff'));
const image = await tiff.getImage();
const data = await image.readRGB({ ...options, interleave: false });
expect(data).to.have.lengthOf(3);
expect(data[0]).to.have.lengthOf(50 * 50);
expect(data[1]).to.have.lengthOf(50 * 50);
expect(data[2]).to.have.lengthOf(50 * 50);
});
```
fixes #424

geotiffimage: stop mentioning that readRGB() forces interleaving

---

.github/changelog.json
.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/release.yml
.github/workflows/version.yml

This PR focuses on updating the GitHub Actions stack and improving the usability of CI and GitHub releases.
I'm happy to make any further changes, just figured a PR with an example diff was a better starting point for discussion than without.
I didn't do much to these workflows, just updated the action and Node.js versions to latest.
I focused my efforts in this PR on `release.yml`, specifically on generating release notes. 
First, I updated all the action versions like above. While doing so, I learned that [`actions/create-release`](https://github.com/actions/create-release) was deprecated in March 2021. They suggest a few alternatives, including [`softprops/action-gh-release`](https://github.com/softprops/action-gh-release), which is [used by …

Workflow updates & release improvements

---

.github/workflows/version.yml

A typo in `version.yml` caused npm version to fail with `pre-*` versions due to a bad `--preid` option addition.
Resolves #466 
I forgot a space when switching from inputted `preId` to hardcoded `preId` 🤦.
I also added a validation step to ensure the workflow doesn't silently fail again in the future.

Fix version.yml typo, validate version output
